- name: create directories for template playbook
  file:
       path: "{{ item }}"
       state: directory
       owner: root
       group: root
       mode: 0755
  loop:
    - ~/ansible_playbook/provision
    - ~/ansible_playbook/provision/roles
    - ~/ansible_playbook/provision/roles/{{name}}
    - ~/ansible_playbook/provision/roles/{{name}}/vars
    - ~/ansible_playbook/provision/roles/{{name}}/default
    - ~/ansible_playbook/provision/roles/{{name}}/templates
    - ~/ansible_playbook/provision/roles/{{name}}/handlers
    - ~/ansible_playbook/provision/roles/{{name}}/files
    - ~/ansible_playbook/provision/roles/{{name}}/meta
    - ~/ansible_playbook/provision/roles/{{name}}/tasks
    - ~/ansible_playbook/provision/inventory
  tags: template




- name: create yaml files for template playbook
  file:
       path: "{{ item }}"
       state: touch
       owner: root
       group: root
       mode: 0755
  loop:
    - ~/ansible_playbook/provision/roles/{{name}}/default/main.yaml
    - ~/ansible_playbook/provision/roles/{{name}}/handlers/main.yaml
    - ~/ansible_playbook/provision/roles/{{name}}/meta/main.yaml
    - ~/ansible_playbook/provision/roles/{{name}}/tasks/main.yaml
    - ~/ansible_playbook/provision/roles/{{name}}/vars/main.yaml
  tags: template


- name: Copy project
  copy:
    src: myproject.yaml
    dest: ~/ansible_playbook/provision/{{name}}.yaml
  tags: template

- name: Copy hosts
  copy:
    src: hosts
    dest: ~/ansible_playbook/provision/inventory/hosts
  tags: template
