- name: check if a variable definded!
  pause:
        prompt: "Enter the name project"
  register: name
  when: name is not defined



- name: create directories for template playbook
  file:
       path: "{{ item }}"
       state: directory
       owner: root
       group: root
       mode: 0755
  loop:
    - ~/{{name.user_input}}_playbook/provision
    - ~/{{name.user_input}}_playbook/provision/roles
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/vars
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/default
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/templates
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/handlers
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/files
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/meta
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/tasks
    - ~/{{name.user_input}}_playbook/provision/inventory
  tags: template




- name: create yaml files for template playbook
  file:
       path: "{{ item }}"
       state: touch
       owner: root
       group: root
       mode: 0755
  loop:
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/default/main.yaml
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/handlers/main.yaml
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/meta/main.yaml
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/tasks/main.yaml
    - ~/{{name.user_input}}_playbook/provision/roles/{{name.user_input}}/vars/main.yaml
  tags: template


- name: Copy project
  copy:
    src: myproject.yaml
    dest: ~/{{name.user_input}}_playbook/provision/{{name.user_input}}.yaml
  tags: template


- name: change project file
  lineinfile:
        path: ~/{{name.user_input}}_playbook/provision/{{name.user_input}}.yaml
        insertafter: "## test"
        line: "        - {{name.user_input}}      #(new)"
        state: present
  tags: template


- name: Copy hosts
  copy:
    src: hosts
    dest: ~/{{name.user_input}}_playbook/provision/inventory/hosts
  tags: template
